### ISSUE TITLE
Build issue if Date does not match system format

### ISSUE THREAD

**Issue by Toyonut** [statiqdev/Statiq#454]
I have a cakebuild script to build my wyam site. Ran fine on my machine, but was failing in an Azure build server. The issue seems to be with the date format in the post. If it matches the system setting, it is OK, if not, you get an error. For example in NZ, the date format is 17/02/2017. On the build agents, it is 02/17/2017. 

`Exception while processing document file:///D:/a/1/s/input/posts/first-post.md in module GenerateFeeds: Could not convert from type String to type Nullable`1 for file:///D:/a/1/s/input/posts/first-post.md while reading published date for feed
            Error while executing module GenerateFeeds
        Error while executing pipeline Feed
Exception during execution: System.InvalidOperationException: Could not convert from type String to type Nullable`1 for file:///D:/a/1/s/input/posts/first-post.md while reading published date for feed
   at Wyam.Common.Configuration.ConfigExtensions.Invoke[T](DocumentConfig config, IDocument document, IExecutionContext context, String errorDetails) in E:\Code\Wyam\src\core\Wyam.Common\Configuration\ConfigExtensions.cs:line 46
   at Wyam.Feeds.GenerateFeeds.<>c__DisplayClass53_0.<Execute>b__0(IDocument input)
   at Wyam.Common.Util.TraceExceptionsExtensions.TraceExceptions(IExecutionContext context, IDocument document, Action`1 action) in E:\Code\Wyam\src\core\Wyam.Common\Util\TraceExceptionsExtensions.cs:line 31
   at Wyam.Common.Util.TraceExceptionsExtensions.ForEach(IExecutionContext context, IEnumerable`1 documents, Action`1 action) in E:\Code\Wyam\src\core\Wyam.Common\Util\TraceExceptionsExtensions.cs:line 108
   at Wyam.Feeds.GenerateFeeds.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.Pipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 documents) in E:\Code\Wyam\src\core\Wyam.Core\Execution\Pipeline.cs:line 252
   at Wyam.Core.Execution.Pipeline.Execute(Engine engine) in E:\Code\Wyam\src\core\Wyam.Core\Execution\Pipeline.cs:line 146
   at Wyam.Core.Execution.Engine.Execute() in E:\Code\Wyam\src\core\Wyam.Core\Execution\Engine.cs:line 198`

**Comment by daveaglick** [comment]
Can you try setting the current culture to match the date format in use and see if that helps?

https://wyam.io/docs/advanced/how-to-set-the-currentculture

**Comment by Toyonut** [comment]
Seems to have worked. Initially I set current culture to en-US on my laptop and put in a US date, MM/dd/yyyy. I still got an error during a build locally. 
For the second test, I set it to en-NZ with a NZ date format, dd/MM/yyyy. I pushed to VSTS and it passed the build. Thanks very much for the help. 
Here is the code on github if that helps. https://github.com/Toyonut/paulsblog

**Comment by daveaglick** [comment]
:+1: 

So are you still having trouble with the US style date, or is everything working okay now?

**Comment by Toyonut** [comment]
Setting to US date format and setting the culture to en-US still does not work on my laptop. Unsure if that is environmental. 
Setting the culture to en-NZ fixes the build agent problem though so that is good. I can write my dates in NZ format, put the culture to en-NZ and the build agent builds correctly. 👍 
Thanks very much.

**Comment by gijswijs** [comment]
I think this issue still persists. It seems to ignore it if the culture is set to en-US in config.wyam, so it defaults to the local settings of your laptop. If that's different than en-US having the date in this format : "3/15/2017" results in an error, but since Azure web apps is by default en-US, having the date in the format 15/3/2017 gives an error during the continuous integration build (if you have set that up)
Specifically using another culture (e.g. en-GB) didn't solve it for me.

Using the date format YYYY-MM-DD solves it without having to set the culture.

**Comment by daveaglick** [comment]
Thanks - I'll take a closer look. Possibly related to #467, or at least can probably address both issues at the same time.

**Comment by daveaglick** [comment]
I've consolidated the date culture issues into #475

**Comment by gijswijs** [comment]
@daveaglick Thanks for your swift response (as always). Wyam.io is a great tool and all your hard work is very much appreciated.
