### ISSUE TITLE
Error while configuring engine: The recipe "Blog" could not be found

### ISSUE THREAD

**Issue by dracan** [statiqdev/Statiq#809]
Following the instructions on the wyam homepage, I get this at step 2...

![image](https://user-images.githubusercontent.com/567988/56210063-e9ee4b80-604c-11e9-9737-b82623088e52.png)

I'm using version 2.2.4.
I've also attached the full output of the command with the `-v` flag in case that's of use.

[output.txt](https://github.com/Wyamio/Wyam/files/3084928/output.txt)

Thank you for your help,
Dan

**Comment by daveaglick** [comment]
Thanks a lot for including the full verbose log - that helps quite a bit. This is actually the second report in a week of package installation failing on a new system, makes me wonder if one of the dependencies has been unlisted or something.

@phillipsj does this look similar to the error you had? Any chance you could add a verbose log too when you get the chance?

I'll start digging...

**Comment by daveaglick** [comment]
I can't repro with a local packages folder (which should be similar since it's not loading packages from a cache):
```
c:\Temp\blogtest>wyam new --recipe Blog --use-local-packages
Wyam version 2.2.4

                ,@@@@@@p
              ,@@@@@@@@@@g
            z@@@@@@@@@@@@@@@
          g@@@@@@@@@@@@@@@@@@@,
        g@@@@@@@@@@@@@@@@@@@@@@@,
      ,@@@@@@@@@@@@@@@@@@@@@@@@@@@
     ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
     $@@@@@@@@@@@@@@@@@@@@@@@@@@@@@c
     @@@@@@@@@@@@@@@@@@@@@@@@B@@@@@@
     @@@@@@@@@@@@@@@@@@@@@@@  j@@@@@
     $@@@@@@@@@@@@@@@@@@@@@F  #@@@@`
      $@@@@@@@@@@@@@@@@@@P   g@@@@P
       %@@@@@@@@@@@@@     ,g@@@@@P
        3@@@@@@@@@@@@@@@@@@@@@@B`
          `%@@@@@@@@@@@@@@@@@P
             `*%RB@@@@@RRP`
**NEW**
Input directory c:/Temp/blogtest/input does not exist and will be created
Configuration file c:/Temp/blogtest/config.wyam does not exist and may be created
Installing NuGet packages
    Installing packages to c:/Temp/blogtest/packages (using local packages folder)
    NuGet packages installed in 27686 ms
Loading assemblies
    Assemblies loaded in 737 ms
Cataloging classes
    Classes cataloged in 204 ms
Cleaning temp path: temp
Cleaned temp directory
```

So the good news is that this doesn't appear to be a universal problem. The bad news is that it's not something obvious like an unlisted dependency and without a repro on my end it'll be harder to debug.

**Comment by daveaglick** [comment]
Another interesting note - this exception appears in the full log:
```
Unexpected exception while installing packages: primarySources
```
which comes from here: https://github.com/Wyamio/Wyam/blob/develop/src/core/Wyam.Configuration/NuGet/PackageInstaller.cs#L221

That trace message just prints out the message from the exception, which means the full exception message was "primarySources". That's not coming from Wyam - the NuGet APIs are throwing that. It's not a particularly helpful exception message, though at least gives us something to go on.

What do you see when you run `nuget sources`? Are all of the listed sources reachable/valid?

**Comment by phillipsj** [comment]
I waited a day and it worked.  I will see if it is still there and post it
up.

**Comment by dracan** [comment]
> "What do you see when you run nuget sources? Are all of the listed
sources reachable/valid?"

I'll try it first thing in the morning. Won't be on my laptop for the rest
of today now. I might try it on my work computer here this afternoon if I
get chance. It's a different computer though (and a different network) - so
will be interesting to see if I still get it. The error I got at lunch was
on my laptop tethered to my phone - although it was a good connection, and
as far as I know they don't block anything.

Thank you for the extremely quick investigations :)

**Comment by dracan** [comment]
I've just tried it on my work PC, and it worked fine. My work PC has never
had wyam installed. I should have pointed out that my own laptop where I
saw this issue did have an older version of wyam installed, and I did a
`dotnet tool upgrade` today before trying it earlier today. So that's one
potential difference - although, doesn't sound related.

**Comment by dracan** [comment]
Just tried it again on my laptop, and it worked fine now. I also tried a `dotnet nuget locals all --clear`, and tried again - and it still worked. This was on my home wifi, so I then tried another clear, then tried when tethered to my phone so it was the same as yesterday - still worked. So does sound like something transient.

**Comment by dracan** [comment]
Also, no mention of that `Unexpected exception while installing packages: primarySources` message now.

**Comment by daveaglick** [comment]
Awesome, glad it's working now. It's possible that NuGet may have been having intermittenet availability problems at the time, or maybe since you were tethering there were issues establishing the TLS connection (I've seen that before while tethering). In any case, I'll close the issue - please open a new one or resurect this one if it happens again.

**Comment by dracan** [comment]
I had it happen again last night when running in a Docker container (so definitely no cache polluting it, as it was building a new container). It worked this morning without any changes on my part.

**Comment by dracan** [comment]
Interestingly, I'm now getting the same error when building the Docker image in Azure DevOps, but it's now working locally. The error I got last night was when running locally. Very strange :(

**Comment by dracan** [comment]
Here's the Dockerfile, if it's of any use...

https://github.com/dotnetoxford/dotnetoxford-website/blob/3e5b3284f908a578a83bedeca2f838737649ec8d/Dockerfile

**Comment by dracan** [comment]
Here's the verbose output from the Azure DevOps build...
[output.log](https://github.com/Wyamio/Wyam/files/3194812/output.log)

With this probably being the relevant bit...

        Installing Wyam.Html 2.2.4.
    Exception while installing packages: One or more errors occurred. (The CancellationTokenSource has been disposed.)
    Error while installing packages, attempting without remote repositories
    Installing package Wyam.Blog 2.2.4
    Unexpected exception while installing packages: primarySources
    Error while installing packages, attempting to continue anyway

Doesn't seem to give too many clues though unfortunately. I've not yet has a successful build of this on Azure DevOps. It's also now failing locally.

> This is actually the second report in a week of package installation failing on a new system, makes me wonder if one of the dependencies has been unlisted or something.

Obviously doing it via Docker means that it's a "new system" every time.

**Comment by dracan** [comment]
Now, I can't get it to work at all even locally. I've tried quite a few times over the past hour too.

**Comment by dracan** [comment]
Interestingly, it seems to work via the zip file (rather than using `dotnet tool install`.

See this change in my Dockerfile...
https://github.com/dotnetoxford/dotnetoxford-website/commit/4141fb57fb1e973bbb7817596157762878706f13#diff-3254677a7917c6c01f55212f86c57fbf

This now works both locally and in Azure Devops, and so far as consistantly worked.

**Comment by daveaglick** [comment]
FYI - I just pushed out a surprise version 2.2.7 of Wyam which should resolve most of these odd NuGet errors people have been seeing. It turns out the version of the NuGet API Wyam is using isn't keeping up with what's going on with package signing and there were incompatibility issues. It  shouldn't have installation problems going forward.

If you're still seeing intermittent package installation failures or getting errors about not being able to find the recipe, give the latest version a spin.

**Comment by dracan** [comment]
Awesome news - thanks for the update :)

**Comment by alexmg** [comment]
I am consistently seeing the same issue with `2.2.7` on my AppVeyor [build](https://ci.appveyor.com/project/alexmg/alexmg/builds/27418766).

[build-log.txt](https://github.com/Wyamio/Wyam/files/3613692/build-log.txt)

I have tried different build images including switching platforms to Ubuntu but the issue persists.

```
Exception while installing packages: NU3000: 
Error while installing packages, attempting without remote repositories
Installing package Wyam.Blog 2.2.7
Unexpected exception while installing packages: primarySources
Error while installing packages, attempting to continue anyway
NuGet packages installed in 10013 ms
```

The [NU3000](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3000) error suggests the problem is one of three issues:

> The package has a primary signature which does not have a timestamp.
> The package has a signature with multiple timestamps.
> The package has a repository counter signature which does not have a timestamp.

The signature and timestamp appear to be valid and pass verification.

```
Signature Hash Algorithm: SHA256
Timestamp: 18/08/2019 5:25:45 AM

Verifying repository primary signature's timestamp with timestamping service certificate:
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: A9A4121063D71D48E8529A4681DE803E3E7954B0
  SHA256 hash: C474CE76007D02394E0DA5E4DE7C14C680F9E282013CFEF653EF5DB71FDF61F8
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 23/12/2017 10:00:00 AM to 23/03/2029 9:59:59 AM

      Subject Name: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
      SHA1 hash: 6FC9EDB5E00AB64151C1CDFCAC74AD2C7B7E3BE4
      SHA256 hash: F3516DDCC8AFC808788BD8B0E840BDA2B5E23C6244252CA3000BB6C87170402A
      Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
      Valid from: 12/01/2016 10:00:00 AM to 12/01/2031 9:59:59 AM

            Subject Name: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
            SHA1 hash: 3679CA35668772304D30A5FB873B0FA77BB70D54
            SHA256 hash: 2399561127A57125DE8CEFEA610DDF2FA078B5C8067F4E828290BFB860E84B3C
            Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
            Valid from: 2/04/2008 10:00:00 AM to 2/12/2037 9:59:59 AM


Signature type: Repository
nuget-v3-service-index-url: https://api.nuget.org/v3/index.json
nuget-package-owners: daveaglick, wyam
Verifying the repository primary signature with certificate:
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA1 hash: 8FB6D7FCF7AD49EB774446EFE778B33365BB7BFB
  SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 10/04/2018 10:00:00 AM to 14/04/2021 10:00:00 PM

      Subject Name: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
      SHA1 hash: 92C1588E85AF2201CE7915E8538B492F605B80C6
      SHA256 hash: 51044706BD237B91B89B781337E6D62656C69F0FCFFBE8E43741367948127862
      Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
      Valid from: 22/10/2013 10:00:00 PM to 22/10/2028 10:00:00 PM

            Subject Name: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
            SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43
            SHA256 hash: 3E9099B5015E8F486C00BCEA9D111EE721FABA355A89BCF1DF69561E3DC6325C
            Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
            Valid from: 10/11/2006 10:00:00 AM to 10/11/2031 10:00:00 AM


Successfully verified package 'Wyam.Blog.2.2.7'.
```

I'm wondering if the NU3000 error is a bit of a catch all, and the actual issue is a failure to contact the timestamping service or something similar to that.

**Comment by alexmg** [comment]
I created a pipeline on Azure DevOps and the build was successful without any other changes. It definitely seems the issue is environmental.

**Comment by daveaglick** [comment]
@alexmg Yeah, that’s the most frustrating part of this bug. It’s been really hard to track down because it works for most people most of the time. But then in very specific environments it’ll give NuGet errors (though those occasionally go away too after a while). I’m pretty sure it has something to do with certificates and thought I disabled certificate checking in the latest version, but people keep reporting the bug.

I’ll be happy when Statiq is out and I don’t have to deal with NuGet APIs anymore.
